### ISSUE TITLE
DNS isn't pointing at GitHub correctly

### ISSUE THREAD

**Issue by christianbundy** [flmd/flmd.github.io#4]
:~(

**Comment by stuartpb** [comment]
The fix for this is in the works.

**Comment by stuartpb** [comment]
Thanks for pointing this out - I'm not sure how this happened (I had the DNS pointed toward CloudFlare, but appear to have forgotten to set it up there), but it should be fixed now.

**Comment by christianbundy** [comment]
Nice, thanks @stuartpb!
